import LocalizedStrings from "react-native-localization";

export const localStrings = new LocalizedStrings({
  en: {
    yes: "yes",
    no: "no",
    login: "Login",
    signup: "Sign Up",
    elderly: "Elderly",
    username: "username",
    password: "password",
    notifications: "Notifications",
    noNotifications: "You do not have any notifications now",
    home: "Home",
    profile: "Profile",
    link: "Link Elderly",
    fillInLinkCode: "Please fill in Link Code",
    linkLater: "link later",
    linkedElderly: "Linked Elderly",
    code: "Code",
    signout: "Sign Out",
    calendar: "Calendar",
  },
  chi: {
    yes: "是",
    no: "否",
    login: "登入",
    signup: "註冊",
    elderly: "老人家",
    username: "用戶名",
    password: "密碼",
    notifications: "通知",
    noNotifications: "您現在沒有任何通知",
    home: "主頁",
    profile: "帳戶",
    link: "連結老人家",
    fillInLinkCode: "請輸入連結碼",
    linkLater: "稍後連結",
    linkedElderly: "已連結之老人家",
    code: "連結碼",
    signout: "登出",
    calendar: "日程",
  },
});
// ? Set the language manually
localStrings.setLanguage("chi");
