import LocalizedStrings from "react-native-localization";

export const localStrings = new LocalizedStrings({
  en: {
    yes: "yes",
    no: "no",
    login: "Login",
    signup: "Sign Up",
    elderly: "Elderly",
    username: "username",
    password: "password",
    notifications: "Notifications",
    noNotifications: "You do not have any notifications now",
    home: "Home",
    profile: "Profile",
    link: "Link Elderly",
    fillInLinkCode: "Please fill in Link Code",
    linkLater: "link later",
    linkedElderly: "Linked Elderly",
    noLinkedElderly: "No Elderly Linked",
    code: "Code",
    signout: "Sign Out",
    calendar: "Calendar",
    noEvents: "No Events",
    title: "Title",
    description: "Description",
    inputTitle: "Please input title",
    inputDescription: "Please input description",
    add: "Add",
    starred: "Starred",
    type: "Type",
    chooseIcon: "Choose Icon",
    dateSelect: "Date",
    timeSelect: "Time",
    newSchedule: "New Schedule",
    editSchedule: "Edit Schedule",
    edit: "Edit",
    delete: "Delete",
    deleteConfirmation:
      "Are you sure you want to delete the selected schedule?",
    cancel: "Cancel",
    elderlyLinkCode: "Elderly Link Code",
    successLinkElderly: "Successfully linked elderly!",
    successAddSchedule: "Successfully added new schedule!",
    successUpdateSchedule: "Successfully updated selected schedule",
    successDeleteSchedule: "Successfully deleted selected schedule",
    successSendNoti: "Successfully sent remind notification",
    elderlyScreen: "Elderly",
    unlinkElderly: "Unlink",
    noUserLinkedError: "No elderly linked",
  },
  chi: {
    yes: "是",
    no: "否",
    login: "登入",
    signup: "註冊",
    elderly: "老人家",
    username: "用戶名",
    password: "密碼",
    notifications: "通知",
    noNotifications: "您現在沒有任何通知",
    home: "主頁",
    profile: "帳戶",
    link: "連結老人家",
    fillInLinkCode: "請輸入連結碼",
    linkLater: "稍後連結",
    linkedElderly: "已連結之老人家",
    noLinkedElderly: "未連結老人家",
    code: "連結碼",
    signout: "登出",
    calendar: "日程",
    noEvents: "沒有日程",
    title: "標題",
    description: "描述",
    inputTitle: "請輸入標題",
    inputDescription: "請輸入描述",
    add: "添加",
    starred: "星星",
    type: "類型",
    chooseIcon: "選擇類型",
    dateSelect: "日期",
    timeSelect: "時間",
    newSchedule: "新事項",
    editSchedule: "更改事項",
    edit: "更改",
    delete: "刪除",
    deleteConfirmation: "確定要刪除已選擇事項?",
    cancel: "取消",
    elderlyLinkCode: "老人家連結碼",
    successLinkElderly: "成功連結老人家!",
    successAddSchedule: "成功增加新事項",
    successUpdateSchedule: "成功更新事項",
    successDeleteSchedule: "成功刪除事項",
    successSendNoti: "成功提醒老人家",
    elderlyScreen: "老人家",
    unlinkElderly: "取消鏈接",
    noUserLinkedError: "沒有連結老人家",
  },
});
// ? Set the language manually
localStrings.setLanguage("chi");
